### ISSUE TITLE
A naive implementaion 

### ISSUE THREAD

**Issue by timechess** [timechess/RACP#6]
Before adding tricks to data process and retrieval methods, we should first implement a naive version with the pipeline below:
1. Use a pretrained model and its tokenizer from huggingface to encode crawled data.
2. Each time the user upload a pdf, we parse it to raw text data and compute the similarity between the upload paper and all the papers' abstracts in our encoded dataset.
3. Take the top n results in last step and compute the similarity between the upload paper and the target whole documents.
4. Sort the result and present them to user.

In short, encode the abstract and whole documents of paper in our dataset separately and construct a vector database. Make sure we can encode new documents in the same way and compute the similarities. We do abstract retrieval first and then whole document.

Any other information that could be added later may be used in step 2 or step 3. Our ranking function should not only consider similarity and relevance but also diversity and quality. However, in this naive implementation, we could ignore that.

This should be done as soon as possible. `similarities` may be a useful toolkit. @CIntellifusion

**Comment by CIntellifusion** [comment]
TO AVOID AWKWARD OF BEING  SELF TALKING OF TIMECHESS：
and as a response of the naive implementation, as well as a summary of communication:
I plan:
1. use summary model to summary abstract into one sentence. 
2. use sentence model to embedding summarized sentience. 
This step model the process of review where reviewers have to first summary then comment advantage and disadvantage.

**Comment by CIntellifusion** [comment]
Design a paper-specific agent task for self-supervised pretraining.
Add comparison with no constrastive learning.
