### ISSUE TITLE
Score function

### ISSUE THREAD

**Issue by timechess** [timechess/RACP#8]
Now our score function consider similarity including `semantic similarity`, `citation similarity` and `author preference`, quality including `author weight`, `citations`, `publication date`.

**Comment by CIntellifusion** [comment]
A detailed description:
semantic similarity : divide the papers in chunks and fuse them, chunks from one paper are labeled as 0.9 , else 0 , and finetuned. And, semantic similarity are also measured across papers using mask and fusion as label
citation similarity: co-citation 
author preference: the author that cooperates relation shipt 
author quality: the total num of citations 
etc.

**Comment by timechess** [comment]
For `citation similarity`, consider some fundamental paper like ResNet with over 100,000 citations from different domains. We need to add a decline factor when calculating similarity. Assume that the citation distribution satisfies power-law distribution, we can get this factor by analyzing the data we crawl now.
